---
# tasks/main.yml

- name: Update apt cache if needed
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages if needed
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"
